services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:3000
    env_file:
      - .env
    
  psql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - psql
    environment:
      ADMINER_DEFAULT_SERVER: psql
    ports:
      - 8080:8080
  

volumes:
  data: 